// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcmxjxrwhptwwujjkklq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbXhqeHJ3aHB0d3d1ampra2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzUzMzQsImV4cCI6MjA2MDk1MTMzNH0.3vM-8faou2oouevHLKHkFL0zP2ZS91gTn7VpdXufNGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);